### PR TITLE
CI and Update for Hexo3

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Upgrading to new api, removing globals

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
some modification still to be done.
I will also set up regression tests

**Comment by tjwudi** [comment]
Seems cool. Ping me when you think it's good to ship :D

**Comment by AdrieanKhisbe** [comment]
add basic regression test + ci badges.
(you'lll just have to activate travis and coveralls)

**Comment by meetwudi** [comment]
L2TM! Thanks!

**Comment by AdrieanKhisbe** [comment]
you're welcome :)
(l2tm? )

**Comment by AdrieanKhisbe** [comment]
(don't forget tag tag v0.1.1 and npm release :) )

**Comment by meetwudi** [comment]
@AdrieanKhisbe L2TM - Looks good to me. :)

**Comment by AdrieanKhisbe** [comment]
lgtm? haha

**Pull request merged**
